version: "3.9"
volumes:
  metasploit:
    external: true

networks:
  default:
    name: vpn
    external: true

services:
  interactive:
    build: interactive
    container_name: interactive
    volumes:
      - ./in:/in
      - ./out:/out
      - metasploit:/var/lib/postgresql
    depends_on:
      - vpn
    # network_mode: "service:vpn"
    tty: true
  nmap:
    build: nmap
    volumes:
      - ./in:in
      - ./out:/out
  john:
    build: john
    volumes:
      - ./in:/in
      - ./out:/out
  msf:
    build: msf
    volumes:
      - ./in:/in
      - ./out:/out
      - metasploit:/var/lib/postgresql

  vpn:
    container_name: vpn
    image: dperson/openvpn-client
    cap_add:
      - net_admin
    volumes:
      - ./vpn.ovpn:/vpn/vpn.conf
    devices:
      - /dev/net/tun
    privileged: true
